### ISSUE TITLE
some problems about DRAI sequences

### ISSUE THREAD

**Issue by hfutball** [DI-HGR/cross_domain_gesture_dataset#2]
Thank you very much for sharing such an excellent paper and dataset. The DRAI sequence is mentioned in the paper. I would like to know if you can share the code for generating the DRAI sequence.

thanks again
hfutball

**Comment by DI-HGR** [comment]
Thanks for the comments. I am sorry that we are not going to share the code yet, since the paper is still under reviewed. We have released both the raw dataset and processed dataset, and we are adding more detailed explanations about the signal processing technique in the revision process, which may help you get a better understanding about it.

**Comment by hfutball** [comment]
> Thanks for the comments. I am sorry that we are not going to share the code yet, since the paper is still under reviewed. We have released both the raw dataset and processed dataset, and we are adding more detailed explanations about the signal processing technique in the revision process, which may help you get a better understanding about it.

Thanks for your reply, I believe your paper will be published soon!
